# NUMPY 

Topics::
- > Difference between python array and numpy
- > Tolist() Array to list
- > Datatype
- > Arange()
- > Zeros
- > Ones
- > Empty
- > Linspace
- > Eye
- > Random
- > Reshape / Resize
- > Concatenate
- > Vstack / Hstack
- > Insert / append
- > Delete
- > Matrix
  Linear-Algebra
- > Invers
- > Matrix_power
- > Solved Linear Equation
- > Determination

In [ ]:
# What is the different between list and numpy array?
# They both accept different datatype strange....:( 
# so, what the different??
# Ans

#.  list = [1,2,3,4,5]     ---> [1][2][3][4][5] --> one node get 32byte's storage mean's 32*8 bittes
#.  array = array[1,2,3,4,5]   ---> [1][2][3][4][5]  --> one node get 8byte's storage mean's 8*8 bittes

# so, array not get more memory as compare to list that mean's less memory less time to run 

# yes, array get less time to run as compare to list....
# that is way array is use for big ML algorithems beacuse array is faster and less memory store....

In [ ]:
# Numpy array divide all argument's same
import numpy as np
array = np.array([3,6,9,12])
print(array/3)
# list can't divide like this
# list = [3,6,9,12]
# list/3

[1. 2. 3. 4.]


In [ ]:
# Array = Collection of element's of same type
# In the python there are two type of arrays
# 1] import array as arr
# 2] import numpy as np


In [ ]:
import array as a
a = a.array('i',[1,2,3])
a = [i for i in a]
print(a)

[1, 2, 3]


In [ ]:
# import numpy as np
# help(np.array)

In [ ]:
import numpy as np
n = np.array([1,2,3,'krupesh'])
print(n)
# Numpy can provide flexible data-field

['1' '2' '3' 'krupesh']


In [ ]:
# Array to convert list == tolist()
import array as arr
array_num = arr.array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print(array_num.tolist())

[1, 3, 5, 3, 7, 1, 9, 3]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.tolist())

[1, 2, 3, 4, 5]


In [ ]:
# we change array datatype
import numpy as np
a = np.array([1,2,3,4.5],complex) # dtype="int"
print(a)

[1. +0.j 2. +0.j 3. +0.j 4.5+0.j]


In [ ]:
# simple way to convert array :: arange
# note :: this one is compulsory given single array
import numpy as np
a = np.arange(10)
# print(a)
a = np.arange(1,10)
# print(a)
a = np.arange(3)
# print(a)
a = np.arange(3,10,2)
# print(a)
a = np.arange(1,10,dtype="int")
# print(a)
a = np.arange(1,10,2,dtype="float")
# print(a)


[3 5 7 9]


In [ ]:
# zeros use
import numpy as np
a = np.zeros(4)
# print(a)
a = np.zeros(3,dtype="int")
# print(a)
a = np.zeros((3,10),dtype="int") # a = np.zeros([3,10],dtype="int")
# print(a)

In [ ]:
# ones use
import numpy as np
a = np.ones([10,100],int)
# print(a)
a = np.ones([10,100,2],int)
# print(a)


In [ ]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

In [ ]:
# empty use
import numpy as np
a = np.empty([3,4],int)
# print(a)

[[    57762928            0 206158430253 193273528375]
 [223338299441 206158430292 249108103221 227633266739]
 [214748364858 197568495669 227633266742 386547056695]]


In [ ]:
# linspace ::
# arange and linspace is almoste same but main difference is 
# the linespace use to equal divide the all aliment's in the array

import numpy as np
a = np.linspace(1,100,num=4,dtype=int,endpoint=False,retstep=True)
# print(a)\
a = np.linspace(1,10,20,dtype=int,endpoint=False,retstep=True) 
# and
# a = np.linspace(1,10,num=20,dtype=int,endpoint=False,retstep=True)
# print(a)
a = np.linspace(1,100,retstep=True)
# print(a)
# if num can't write then it is automaticaly consider 50 values.


In [ ]:
# eye ::
# this is very intresting function
import numpy as np
a = np.eye(5,dtype='int')
# print(a)
a = np.eye(10,dtype="int")
# print(a)
a = np.eye(5,k=1,dtype="int")
# print(a)
a = np.eye(5,k=2,dtype="int")
# print(a)
a = np.eye(5,k=-1,dtype="int")
# print(a)
a = np.eye(5,k=-2,dtype="int")
# print(a)
a = np.eye(2,3,k=1)
# print(a)


# identy::
# identy and eye both work is same
import numpy as np
a = np.identity(2)
# print(a)
# help(np.identity)
# identity is automaticaly consider matrix 

In [ ]:
# random.rand
import numpy as np
a = np.random.rand(3,2)
# print(a)
a = np.random.rand(3,5,2)
# print(a)
a = np.random.randint(3,size=10)
# print(a)
a = np.random.seed(0)
# print(a)
a = np.random.permutation(10) # output given by 0 to 10 random choice number and give only 10 number's
# print(a)

In [137]:

# indexing
a = np.arange(0,12).reshape(2,2,3)
# print(a)
a[-2,-1,-2]

4

In [199]:
# slicing
import numpy as np
a = np.arange(10)
# print(a)
b = [a[1:4],a[-4:-2]]
# print(np.concatenate(b))
a = np.arange(12).reshape(2,2,3)
# print(a)
b = [a[0,0,1],a[0,1,1],a[-1,-2,-2],a[-1,-1,-2]]
# print(b)
a = np.arange(1,10)
# print(a)
index = np.array([1,4,5])
a[index]
a[[1,4,5]]
a = np.arange(1,10).reshape(3,3)
# print(a)
b = [a[0,:2],a[1,1:],a[2,:2]]
# print(np.concatenate(b))
a = np.arange(1,10).reshape(3,3)
# print(a)
# print(a[[0,1,2],[0,1,2]])

In [221]:
# Arithmetic opration
import numpy as np
a = np.arange(1,10).reshape(3,3)
# print(a)
# print(a[a>5]+50)\
# print(a+2*2)
# print(a**a)
# we are directly add two array with help of arithmetic oprator
a = np.random.randint(1,7,size=(2,3))
b = np.random.randint(1,7,size=(2,3))
# print(a**b)
# print(a+b)


[[  8   5  64]
 [  5  16 256]]
[[5 6 8]
 [6 6 8]]


In [242]:
# reshape process
import numpy as np
a = np.arange(1,10).reshape(3,3)
# print(a)
a = np.array([1,2,3,4,5,"krupesh"])
a = np.resize(a,(8,8))
# print(a)


In [246]:
# Flatten function & reavel function
import numpy as np
a = np.arange(1,10).reshape(3,3)
# print(a.flatten())
print(a.ravel())

[1 2 3 4 5 6 7 8 9]


In [254]:
# Transfert fuction::
# Transfert function change shape of array like (5,2)--->(2,5)
import numpy as np
a = np.arange(1,11).reshape(5,2)
# print(a)
# np.transpose(a)
a = np.arange(1,25).reshape(2,3,4)
# print(a)
# np.transpose(a) # (2,3,4)----->(4,3,2)
# np.transpose(a,(1,0,2)) # (2,3,4)----->(3,2,4)
# a.transpose((1,0,2))
# a.T


In [260]:
# copy array
import numpy as np
a = np.arange(1,5)
b = np.arange(10)
c = np.arange(6)
np.concatenate((a,c),out=b)
print(b)

[1 2 3 4 0 1 2 3 4 5]


In [397]:
## Axis MIMP
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis=0)
np.concatenate((a,b.T),axis=1)
np.vstack((a,b)) # atuomaticaly consider 0 axis
np.hstack((a,b.T)) # automaticaly consider 1 axis

array([[1, 2, 5],
       [3, 4, 6]])

In [282]:
# split method
import numpy as np
a = np.arange(10)
# np.split(a,3)
# np.split(a,2)


In [401]:
## Add query
import numpy as np
a = np.arange(1,11)
np.insert(a,1,5)
np.insert(a,1,50.2) #It's automaticaly convert into int
np.insert(a,(1,3),5) # This is set 5 into two space
#########################
a = np.array([[1,2],[3,4]])
np.insert(a,1,23) # This function first convert 1-D array then add
np.insert(np.split(a,1),0,23,axis=0)
np.insert(np.split(a,2),1,23,axis=0)
np.insert(a,1,[1,2],axis=0)
################################
# append alway's add last side value
a = np.arange(10)
b = np.arange(10)
np.append(b,a)
np.append(a,[[4,5]])
#################################
# In the numpy array can append do extend work also.....
###########################################
# Delete::
a = np.array([[1,2],[3,4]])
np.delete(a,2) # first convert 1-D array the delete
np.delete(a,1,-2) # This is delete only single value
np.delete(a,1,axis=0) # It's consider as a row wise so, 1 row deleted
np.delete(a,1,axis=1) # It's consider as column wise so, 1 column value deleted
a = np.random.randint(1,10,size=(3,3,3))
print(a)
np.delete(a,1,0) # 0 is the axis consider
np.delete(a,2,axis=0)
np.delete(a,2,1)
np.delete(a,1,2)


[[[3 1 5]
  [5 2 5]
  [7 6 6]]

 [[1 3 5]
  [9 8 2]
  [5 6 9]]

 [[3 7 7]
  [8 2 7]
  [9 2 1]]]


array([[[3, 5],
        [5, 5],
        [7, 6]],

       [[1, 5],
        [9, 2],
        [5, 9]],

       [[3, 7],
        [8, 7],
        [9, 1]]])

In [400]:
# Axis :::::::::
# What is Axis??
# Axis is consider into imagination
# 0 mean's hole array outside part
# 1 mean's hole array 1 step inside part
# 2 mean's hole array inside column's countable
# -1 mean's hole array count inside to outside path follow(It's consider as 2 column's)
# -2 mean's second part into -1 (It's consider as 1 row wise)
# -3 mean's hole array outside part of array


In [403]:
# Matrix Multiplication
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
a*b # This is simple multiplication
######################
# Real type of multiplication
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
a.dot(b)

array([[ 70, 100],
       [150, 220]])

In [407]:
# Matrix write different style
import numpy as np
a = np.matrix("1 2;3 4;5 6")
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [416]:
## Real method of linear-algebra
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.linalg.inv(a)
b  # A = 1/A
# Equation = 1/(ad-bc)*[[d -b],
#                       [-c a]]
# How to check the array is Revers or not
np.allclose(np.dot(a,b),np.eye(2))

True

In [440]:
# Matrix_power
import numpy as np
a = np.arange(1,10).reshape(3,3)
# np.linalg.matrix_power(a,2) # a*2
# np.dot(a,a)  # a*a
# np.linalg.matrix_power(a,0) # it's automaticaly consider to eye mathod
# np.linalg.matrix_power(a,4)

In [445]:
# Solved linear equation
# 3x + y = 9
# x + 2y = 8
import numpy as np
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)
x = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
y = np.array([13,13,26])
np.linalg.solve(x,y)

array([2., 3., 1.])

In [451]:
# Determinate
import numpy as np
a = np.array([[1,2],[3,4]])
# print(a)
np.linalg.det(a) # ANS = 1*4 - 2*3
round(np.linalg.det(a)) # Roundfigure show
b = np.arange(0,9).reshape(3,3)
# print(b)
np.linalg.det(b)

0.0